### ISSUE TITLE
PyCon Cleveland

### ISSUE THREAD

**Issue by andrealmar** [dunossauro/calendario-de-eventos#14]
Porque tem PyCon Cleveland se a idéia é ser um repositório de eventos no Brasil? 🤔

**Comment by dunossauro** [comment]
Opa, se quiser mandar um pr removendo. Será aceito

**Comment by Serrones** [comment]
Aberto [PR](https://github.com/dunossauro/calendario-de-eventos/pull/18) para remoção da PyCon Cleveland

**Comment by Serrones** [comment]
@schneiderl , acredito que pode fechar essa issue

**Comment by schneiderl** [comment]
@Serrones consegue alterar a descrição daquela pull request? Adicionar o seguinte: "Closes #<numero_da_issue>" faz com que a issue seja fechada automaticamente quando a pull request for merged ao repositório.

**Comment by schneiderl** [comment]
Nesse caso especifico, teria que ser adicionado algo como "Closes #14".

**Comment by Serrones** [comment]
Feito, @schneiderl 
Valeu pela dica

**Comment by schneiderl** [comment]
@Serrones funciona também no titulo :)

**Comment by Serrones** [comment]
Boa @schneiderl 
Mais um aprendizado pra gente!!
Vlww
